spring:
  profiles: unittest
  datasource:
    url: jdbc:h2:mem:rs;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username:
    password:
  jpa:
    show-sql: false
    transaction-timeout: 3000
    hibernate:
      ddl-auto: update
    database-platform: H2
  flyway:
    enabled: false
id-generator:
  instance-id: 0
server:
  port:
management:
  server:
    port:
auth:
  endpoint:
  client:
  secret:

contact:
  endpoint: https://contact-test-uri.com