/*
 * RESERVATION SERVICE REST API
 * API for the Reservation Service. The API covers the functionality to create, read and update reservations and their metadata stored in the DAM metadata store, add and remove assets from the reservations.  The API is based on REST and only consumes JSON requests.  **Security**  This API is protected via the standard OIDC authentication provided by MIT. In order to use the API, an access token must be retrieved first and then used in the Authorization header with \"Bearer [Access Token]\". 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rs.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.rs.client.model.AssetReservationMeta;
import com.rs.client.model.ReservationStatus;
import com.rs.client.model.Type;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AssetReservation
 */

public class AssetReservation {
  @SerializedName("_meta")
  private AssetReservationMeta meta = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("type")
  private Type type = null;

  @SerializedName("status")
  private ReservationStatus status = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("created")
  private String created = null;

  @SerializedName("lastModified")
  private String lastModified = null;

  @SerializedName("assetsCount")
  private Integer assetsCount = null;

  public AssetReservation meta(AssetReservationMeta meta) {
    this.meta = meta;
    return this;
  }

   /**
   * Get meta
   * @return meta
  **/
  @ApiModelProperty(value = "")
  public AssetReservationMeta getMeta() {
    return meta;
  }

  public void setMeta(AssetReservationMeta meta) {
    this.meta = meta;
  }

  public AssetReservation id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AssetReservation type(Type type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")
  public Type getType() {
    return type;
  }

  public void setType(Type type) {
    this.type = type;
  }

  public AssetReservation status(ReservationStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(required = true, value = "")
  public ReservationStatus getStatus() {
    return status;
  }

  public void setStatus(ReservationStatus status) {
    this.status = status;
  }

  public AssetReservation title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public AssetReservation created(String created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public String getCreated() {
    return created;
  }

  public void setCreated(String created) {
    this.created = created;
  }

  public AssetReservation lastModified(String lastModified) {
    this.lastModified = lastModified;
    return this;
  }

   /**
   * Get lastModified
   * @return lastModified
  **/
  @ApiModelProperty(value = "")
  public String getLastModified() {
    return lastModified;
  }

  public void setLastModified(String lastModified) {
    this.lastModified = lastModified;
  }

  public AssetReservation assetsCount(Integer assetsCount) {
    this.assetsCount = assetsCount;
    return this;
  }

   /**
   * Get assetsCount
   * @return assetsCount
  **/
  @ApiModelProperty(value = "")
  public Integer getAssetsCount() {
    return assetsCount;
  }

  public void setAssetsCount(Integer assetsCount) {
    this.assetsCount = assetsCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssetReservation assetReservation = (AssetReservation) o;
    return Objects.equals(this.meta, assetReservation.meta) &&
        Objects.equals(this.id, assetReservation.id) &&
        Objects.equals(this.type, assetReservation.type) &&
        Objects.equals(this.status, assetReservation.status) &&
        Objects.equals(this.title, assetReservation.title) &&
        Objects.equals(this.created, assetReservation.created) &&
        Objects.equals(this.lastModified, assetReservation.lastModified) &&
        Objects.equals(this.assetsCount, assetReservation.assetsCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(meta, id, type, status, title, created, lastModified, assetsCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetReservation {\n");
    
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    assetsCount: ").append(toIndentedString(assetsCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

