/*
 * RESERVATION SERVICE REST API
 * API for the Reservation Service. The API covers the functionality to create, read and update reservations and their metadata stored in the DAM metadata store, add and remove assets from the reservations.  The API is based on REST and only consumes JSON requests.  **Security**  This API is protected via the standard OIDC authentication provided by MIT. In order to use the API, an access token must be retrieved first and then used in the Authorization header with \"Bearer [Access Token]\". 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rs.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.rs.client.model.Link;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AssetReservationMetaLinks
 */

public class AssetReservationMetaLinks {
  @SerializedName("reservations")
  private Link reservations = null;

  @SerializedName("assets")
  private Link assets = null;

  @SerializedName("self")
  private Link self = null;

  public AssetReservationMetaLinks reservations(Link reservations) {
    this.reservations = reservations;
    return this;
  }

   /**
   * Get reservations
   * @return reservations
  **/
  @ApiModelProperty(required = true, value = "")
  public Link getReservations() {
    return reservations;
  }

  public void setReservations(Link reservations) {
    this.reservations = reservations;
  }

  public AssetReservationMetaLinks assets(Link assets) {
    this.assets = assets;
    return this;
  }

   /**
   * Get assets
   * @return assets
  **/
  @ApiModelProperty(required = true, value = "")
  public Link getAssets() {
    return assets;
  }

  public void setAssets(Link assets) {
    this.assets = assets;
  }

  public AssetReservationMetaLinks self(Link self) {
    this.self = self;
    return this;
  }

   /**
   * Get self
   * @return self
  **/
  @ApiModelProperty(required = true, value = "")
  public Link getSelf() {
    return self;
  }

  public void setSelf(Link self) {
    this.self = self;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssetReservationMetaLinks assetReservationMetaLinks = (AssetReservationMetaLinks) o;
    return Objects.equals(this.reservations, assetReservationMetaLinks.reservations) &&
        Objects.equals(this.assets, assetReservationMetaLinks.assets) &&
        Objects.equals(this.self, assetReservationMetaLinks.self);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reservations, assets, self);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetReservationMetaLinks {\n");
    
    sb.append("    reservations: ").append(toIndentedString(reservations)).append("\n");
    sb.append("    assets: ").append(toIndentedString(assets)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

