/*
 * RESERVATION SERVICE REST API
 * API for the Reservation Service. The API covers the functionality to create, read and update reservations and their metadata stored in the DAM metadata store, add and remove assets from the reservations.  The API is based on REST and only consumes JSON requests.  **Security**  This API is protected via the standard OIDC authentication provided by MIT. In order to use the API, an access token must be retrieved first and then used in the Authorization header with \"Bearer [Access Token]\". 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rs.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.rs.client.model.FieldMeta;
import com.rs.client.model.FilterSuggestion;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ReservationSuggestions
 */

public class ReservationSuggestions {
  @SerializedName("_meta")
  private FieldMeta meta = null;

  @SerializedName("fulltextSuggestions")
  private List<Object> fulltextSuggestions = null;

  @SerializedName("filterSuggestions")
  private List<FilterSuggestion> filterSuggestions = null;

  public ReservationSuggestions meta(FieldMeta meta) {
    this.meta = meta;
    return this;
  }

   /**
   * Get meta
   * @return meta
  **/
  @ApiModelProperty(value = "")
  public FieldMeta getMeta() {
    return meta;
  }

  public void setMeta(FieldMeta meta) {
    this.meta = meta;
  }

  public ReservationSuggestions fulltextSuggestions(List<Object> fulltextSuggestions) {
    this.fulltextSuggestions = fulltextSuggestions;
    return this;
  }

  public ReservationSuggestions addFulltextSuggestionsItem(Object fulltextSuggestionsItem) {
    if (this.fulltextSuggestions == null) {
      this.fulltextSuggestions = new ArrayList<Object>();
    }
    this.fulltextSuggestions.add(fulltextSuggestionsItem);
    return this;
  }

   /**
   * Get fulltextSuggestions
   * @return fulltextSuggestions
  **/
  @ApiModelProperty(value = "")
  public List<Object> getFulltextSuggestions() {
    return fulltextSuggestions;
  }

  public void setFulltextSuggestions(List<Object> fulltextSuggestions) {
    this.fulltextSuggestions = fulltextSuggestions;
  }

  public ReservationSuggestions filterSuggestions(List<FilterSuggestion> filterSuggestions) {
    this.filterSuggestions = filterSuggestions;
    return this;
  }

  public ReservationSuggestions addFilterSuggestionsItem(FilterSuggestion filterSuggestionsItem) {
    if (this.filterSuggestions == null) {
      this.filterSuggestions = new ArrayList<FilterSuggestion>();
    }
    this.filterSuggestions.add(filterSuggestionsItem);
    return this;
  }

   /**
   * Get filterSuggestions
   * @return filterSuggestions
  **/
  @ApiModelProperty(value = "")
  public List<FilterSuggestion> getFilterSuggestions() {
    return filterSuggestions;
  }

  public void setFilterSuggestions(List<FilterSuggestion> filterSuggestions) {
    this.filterSuggestions = filterSuggestions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReservationSuggestions reservationSuggestions = (ReservationSuggestions) o;
    return Objects.equals(this.meta, reservationSuggestions.meta) &&
        Objects.equals(this.fulltextSuggestions, reservationSuggestions.fulltextSuggestions) &&
        Objects.equals(this.filterSuggestions, reservationSuggestions.filterSuggestions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(meta, fulltextSuggestions, filterSuggestions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReservationSuggestions {\n");
    
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    fulltextSuggestions: ").append(toIndentedString(fulltextSuggestions)).append("\n");
    sb.append("    filterSuggestions: ").append(toIndentedString(filterSuggestions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

